spring:
  config:
    activate:
      on-profile: prod
  cloud:
    inetutils:
      preferredNetworks:
        - 10.0.0.0/24

eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
    prefer-ip-address: true
    ip-address: ${HOST_IP:127.0.0.1}
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
