spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    register-with-eureka: false # Disable registering of the Eureka server itself
    fetch-registry: false # Disable fetching registry information from the Eureka server
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
